language: python
python:
  - "2.7"
env:
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
matrix:
  include:
    - python: 3.5
      env:
      - TOX_ENV=py35
addons:
  apt_packages:
    - pandoc
before_install:
  - sudo apt-get update -qq
  - sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
install:
  - pip install tox==2.0.1
script: tox -e $TOX_ENV
notifications:
  irc:
    channels:
      - "irc.freenode.org#pelican"
    on_success: change
