# Site settings
title: Shuest 
description: "Shuest blog"


# Build settings
permalink: /posts/:title
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [autolink, no_intra_emphasis, strikethrough, tables, lax_spacing, space_after_headers, superscript]

assets:
  cache: false
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor

author:
  full_name: Shu Zhan
  username: Shuest
  email: 391077005@qq.com

  facebook: cedric.vec.io
